# Generated by Django 5.0.1 on 2024-10-15 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoboMedellin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_hecho', models.DateTimeField()),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('sexo', models.CharField(max_length=10)),
                ('edad', models.IntegerField()),
                ('medio_transporte', models.CharField(max_length=50)),
                ('modalidad', models.CharField(max_length=100)),
                ('nombre_barrio', models.CharField(max_length=100)),
                ('codigo_comuna', models.IntegerField()),
                ('codigo_comuna2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tweet_text', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('Civil', 'Civil'), ('Administrador', 'Administrador')], default='Civil', max_length=20)),
                ('suscripcion', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Robo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Vehículos', 'Vehiculos'), ('Peatones', 'Peatones'), ('Viviendas', 'Viviendas')], max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_hora', models.DateTimeField()),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
        ),
    ]
